import { useState } from 'react'
import Head from 'next/head'
import { BsFillMoonStarsFill, BsTelegram } from 'react-icons/bs'
import { AiFillGithub } from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/image.webp'
import codingSkill from '../public/pc.png'
import otherSkill from '../public/other.webp'
import designSkill from '../public/design.webp'
import menuReact from '../public/menu-react.jpg'
import photosReact from '../public/photos-react.jpg'
import glassLayout from '../public/glass-layout.jpg'
import hoverTable from '../public/hover-table.jpg'
import laslesLayout from '../public/lasles-layout.jpg'
import questions from '../public/question.jpg'
import reactCards from '../public/react-cards.jpg'
import smoothieLayout from '../public/smoothie-layout.jpg'
import squad from '../public/squad.jpg'
import unsplashProject from '../public/unsplash-project.jpg'
import react from 'react'

export default function Home() {
  const objSkills = [
    {
      _id: 'first-skill',
      urlImg: codingSkill,
      name: 'Программирование',
      description:
        'Основные инструменты которые я использую для программирования.',
      tools: ['VS Code', 'JavaScript', 'Node', 'React'],
    },
    {
      _id: 'second-skill',
      urlImg: designSkill,
      name: 'Дизайн',
      description:
        'Создаю дизайны на свой вкус, которые в дальнейшем использую.',
      tools: ['Figma', 'Photoshop'],
    },
    {
      _id: 'other-skill',
      urlImg: otherSkill,
      name: 'Soft-скиллы',
      description: 'Основные софт-скиллы :).',
      tools: [
        'Коммуникабельность',
        'Работа в коллективе',
        'Личная эффективность',
      ],
    },
  ]

  const projects = [
    {
      _id: 'menuReact',
      urlImage: menuReact,
      urlGit: 'https://github.com/ArcticGa/MainJsPractices',
    },
    {
      _id: 'photosReact',
      urlImage: photosReact,
      urlGit: 'https://github.com/ArcticGa/ReactPracticeProjects',
    },
    {
      _id: 'unsplash',
      urlImage: unsplashProject,
      urlGit: 'https://github.com/ArcticGa/UnsplashReactProject',
    },
    {
      _id: 'glassLayout',
      urlImage: glassLayout,
      urlGit: 'https://github.com/ArcticGa/GlassLayoutProject',
    },
    {
      _id: 'smoothie',
      urlImage: smoothieLayout,
      urlGit: 'https://github.com/ArcticGa/SmoothieLayoutProject',
    },
    {
      _id: 'squad',
      urlImage: squad,
      urlGit: 'https://github.com/ArcticGa/squad-project',
    },
    {
      _id: 'reactCards',
      urlImage: reactCards,
      urlGit: 'https://github.com/ArcticGa/ReactCardsProject',
    },
    {
      _id: 'lasles',
      urlImage: laslesLayout,
      urlGit: 'https://github.com/ArcticGa/LaslesProject-layout',
    },
    {
      _id: 'question',
      urlImage: questions,
      urlGit: 'https://github.com/ArcticGa/QuestionsReactFirebaseProject',
    },
    {
      _id: 'hoverTable',
      urlImage: hoverTable,
      urlGit: 'https://github.com/ArcticGa/MainJsPractices',
    },
  ]

  const [darkMode, setDarkMode] = useState(true)

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Aleksandr Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">devalex</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1_tnQAIGWPqJfA9DWBnzalpQZ81Q34U3X/view?usp=share_link"
                >
                  Резюме
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Aleksandr
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Junior JavaScript Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              JavaScript разработчик, дизайнер, студент. Присоединяйся ко мне,
              вместе будем кодить.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-10 py-1 text-gray-600 dark:text-gray-400">
            <a href="https://t.me/dev_aleks" target="_blank" rel="noreferrer">
              <BsTelegram />
            </a>
            <a
              href="https://github.com/ArcticGa"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillGithub />
            </a>
          </div>
          <div className="py-5">
            <Image
              className="mx-auto rounded-2xl bg-gray-900"
              src={deved}
              alt="image"
              width={500}
              height={500}
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Мои навыки</h3>
            <p className="text-lg leading-8 text-gray-800 dark:text-gray-300">
              Основные навыки программирования и коммуникации, которыми я
              обладаю.
            </p>
          </div>
          <div className="lg:flex gap-10">
            {objSkills.map((obj) => (
              <div
                key={obj._id}
                className="text-center text-lg shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-100"
              >
                <Image
                  src={obj.urlImg}
                  width={150}
                  height={150}
                  alt="image"
                  className="mx-auto"
                />
                <h3 className="text-lg font-medium pt-8 pb-2">{obj.name}</h3>
                <p className="py-2">{obj.description}</p>
                <h4 className="py-4 text-teal-600">
                  Навыки, которыми я обладаю
                </h4>
                <div className="flex flex-wrap">
                  {obj.tools.map((tool) => (
                    <p
                      key={tool}
                      className="text-white p-2 rounded-lg flex-1 bg-gray-700 m-1 min-w-fit"
                    >
                      {tool}
                    </p>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Портфолио</h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-400">
              В данном разделе можно посмотреть все мои проекты, включая
              <span className="text-teal-500"> Вёрстку, </span>
              <span className="text-teal-500">
                JavaScript проекты и плагины
              </span>
              , а так же <span className="text-teal-500">React </span>
              приложения.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-400">
              Прокты расположены по сложности. От больших к маленьким. Остальные
              проекты находятся в моем профиле на GitHub.
            </p>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            {projects.map((project) => (
              <div key={project._id} className="basis-1/3 flex-1 ">
                <a target="_blank" rel="noreferrer" href={project.urlGit}>
                  <Image
                    className="rounded-xl object-cover"
                    src={project.urlImage}
                    alt="website-image"
                    width={'100%'}
                    height={'100%'}
                  />
                </a>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}
